name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  list-environments:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.listens.output.colors}}
    steps:
      - name: Define list environments
        id: listenvs
        run: |
          echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"
 
  deploy-application:
    runs-on: ubuntu-latest
    needs:
    - list-environments
    strategy:
      matrix:
        envv: ${{ fromJSON(needs.list-environments.outputs.listenvs) }}

    steps:
    - name: Report Env
      run: |
        cat environments
